services:
  - type: web
    name: medis-backend
    runtime: python
    rootDir: ml
    buildCommand: pip install -r ml/requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
